# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-06 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import notifications.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('identifier', models.CharField(db_index=True, max_length=100, unique=True)),
                ('secret', models.UUIDField()),
                ('email', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('text_message', models.TextField(null=True)),
                ('html_message', models.TextField(null=True)),
                ('sms_message', models.CharField(max_length=160, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('event', enumfields.fields.EnumField(enum=notifications.enums.WebhookEvent, max_length=100, null=True)),
                ('to_email', models.CharField(max_length=75, null=True)),
                ('to_mobile', models.CharField(max_length=75, null=True)),
                ('expression', models.CharField(max_length=150, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('identifier', models.UUIDField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notifications.User'),
        ),
    ]
