# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-20 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('recipient', models.CharField(max_length=150)),
                ('text_message', models.TextField(null=True)),
                ('html_message', models.TextField(null=True)),
                ('sms_message', models.CharField(max_length=300, null=True)),
                ('sent', models.BooleanField(default=True)),
                ('error_message', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sms_message',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to_email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to_mobile',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.Notification'),
        ),
    ]
