# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-28 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20170720_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
