# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-12 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='expression',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='html_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sms_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to_mobile',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
