PROJECT_NAME: ico-service
NAMESPACE: ico-service
IMAGE: gcr.io/rehive-services/ico-service
HOST_NAME: ico-service
VIRTUAL_HOST: ico.services.rehive.io
ENV_FILE: .local.env
VENV_PYTHON: ~/.conda/envs/ico-service/bin/python
POSTGRES_PORT: 5126