PROJECT_NAME: notification-service
NAMESPACE: notification-service
IMAGE: gcr.io/rehive-services/notification-service
HOST_NAME: notification-service
VIRTUAL_HOST: notification.services.rehive.io
ENV_FILE: .local.env
CELERY_ID: notification-service
VENV_PYTHON: ~/.conda/envs/notification-service/bin/python
POSTGRES_PORT: 5125