PROJECT_NAME: notification-service
NAMESPACE: notification-service
IMAGE: gcr.io/rehive-services/notification-service
HOST_NAME: rehive-build-server # not required for k8s-only setup
BASE_IMAGE: gcr.io/rehive-services/notification-service-base
VIRTUAL_HOST: notification.services.rehive.io
ENV_FILE: .production.env
CELERY_ID: notification-service-kube
GCLOUD_STATIC_BUCKET: notification-service-static
CLUSTER: production
CLUSTER_PROJECT: rehive-services