version: "2.1"

services:
  webapp:
    extends:
      service: webapp
      file: ./docker-services.yml
    command: /bin/sh -c "gunicorn config.wsgi:application --config file:config/gunicorn.py"
    links:
      - postgres
    ports:
      - 8010:8000

  postgres:
    image: postgres:9.5
    volumes_from:
      - db_data
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
    - ${ENV_FILE}
    restart: always

  db_data:
    image: postgres
    command: echo "DB data volume!"
    volumes:
      - /var/lib/postgresql/data
