# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-18 08:50
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import ico.enums
import ico.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('identifier', models.CharField(db_index=True, max_length=100, unique=True)),
                ('secret', models.UUIDField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('code', models.CharField(db_index=True, max_length=12)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('symbol', models.CharField(blank=True, max_length=30, null=True)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('divisibility', models.IntegerField(default=2)),
                ('enabled', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ico.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('number', models.IntegerField()),
                ('exchange_provider', models.CharField(max_length=200, null=True)),
                ('fiat_goal_amount', ico.models.MoneyField(decimal_places=18, default=Decimal('0'), max_digits=28)),
                ('enabled', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ico.Company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ico', to='ico.Currency')),
                ('fiat_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ico_fiat', to='ico.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('level', models.IntegerField()),
                ('percentage', models.IntegerField(default=100)),
                ('fiat_rate', ico.models.MoneyField(decimal_places=18, default=Decimal('0'), max_digits=28)),
                ('ico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ico.Ico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('desposit_tx', models.CharField(max_length=200, null=True)),
                ('token_tx', models.CharField(max_length=200, null=True)),
                ('status', enumfields.fields.EnumField(enum=ico.enums.PurchaseStatus, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('deposit_amount', ico.models.MoneyField(decimal_places=18, default=Decimal('0'), max_digits=28)),
                ('token_amount', ico.models.MoneyField(decimal_places=18, default=Decimal('0'), max_digits=28)),
                ('rate', ico.models.MoneyField(decimal_places=18, default=Decimal('0'), max_digits=28)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ico.Phase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('rate', ico.models.MoneyField(decimal_places=18, default=Decimal('0'), max_digits=28)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ico.Currency')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ico.Phase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('identifier', models.UUIDField()),
                ('token', models.CharField(max_length=200, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ico.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ico.User'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ico.Quote'),
        ),
        migrations.AddField(
            model_name='company',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_company', to='ico.User'),
        ),
    ]
