# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-18 18:54
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def create_cache_table(apps, schema_editor):
    call_command('createcachetable')


class Migration(migrations.Migration):

    dependencies = [
        ('ico', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_cache_table)
    ]
