# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-17 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ico', '0002_auto_20170817_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ico',
            name='fiat_rate',
        ),
        migrations.AddField(
            model_name='currency',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
