# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-20 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ico', '0002_auto_20170818_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='desposit_tx',
        ),
        migrations.AddField(
            model_name='purchase',
            name='deposit_tx',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='token_tx',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
