# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-21 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ico', '0003_auto_20170820_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ico',
            old_name='fiat_goal_amount',
            new_name='base_goal_amount',
        ),
        migrations.RenameField(
            model_name='phase',
            old_name='fiat_rate',
            new_name='base_rate',
        ),
        migrations.RemoveField(
            model_name='ico',
            name='fiat_currency',
        ),
        migrations.AddField(
            model_name='ico',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ico_base', to='ico.Currency'),
            preserve_default=False,
        ),
    ]
