# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-25 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ico', '0005_auto_20170822_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ico',
            name='exchange_provider',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
