# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-06 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ico', '0007_ico_amount_remaining'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('message', models.CharField(max_length=300)),
                ('exception', models.CharField(blank=True, max_length=300, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ico.Purchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
