# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-08 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ico', '0009_auto_20170907_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='ico',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
