# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-11 10:34
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import ico.models


class Migration(migrations.Migration):

    dependencies = [
        ('ico', '0010_ico_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ico',
            name='max_purchase_amount',
            field=ico.models.MoneyField(decimal_places=18, default=Decimal('0'), max_digits=28),
        ),
        migrations.AlterField(
            model_name='ico',
            name='min_purchase_amount',
            field=ico.models.MoneyField(decimal_places=18, default=Decimal('0'), max_digits=28),
        ),
    ]
