# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-11 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ico', '0011_auto_20170911_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='ico',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phase',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
