# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-13 14:55
from __future__ import unicode_literals

from django.db import migrations
import enumfields.fields
import ico.enums


class Migration(migrations.Migration):

    dependencies = [
        ('ico', '0012_auto_20170911_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ico',
            name='enabled',
        ),
        migrations.AddField(
            model_name='ico',
            name='status',
            field=enumfields.fields.EnumField(default='hidden', enum=ico.enums.IcoStatus, max_length=50),
        ),
    ]
