kind: PersistentVolume
apiVersion: v1
metadata:
  name: ico-service-staging-database-volume
  labels:
    release: "staging"
  namespace: ico-service-staging
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "ico-service-staging-database"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ico-service-data-claim
  namespace: ico-service-staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  selector:
    matchLabels:
      release: "staging"
---
apiVersion: v1
kind: Pod
metadata:
  name: database-postgres
  namespace: ico-service-staging
  labels:
    name: database
    node: postgres
spec:
  containers:
    -
      name: postgres
      image: postgres
      ports:
        -
          containerPort: 5432
      env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pg-data-volume
  volumes:
    - name: pg-data-volume
      persistentVolumeClaim:
        claimName: ico-service-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: database-postgres-service
  namespace: ico-service-staging
  labels:
    name: database
    node: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  externalIPs:
    - 192.168.99.100
  selector:
    name: database
    node: postgres